const articles: BlogArticle[] = [
  {
    title: "The Geometry of Fairness — When Metrics Route Morality",
    excerpt:
      "A critical look at fairness metrics: what they capture, what they obscure, and how they shape ethical choices in model design.",
    readTime: "9 min read",
    publishDate: "Feb 2025",
    category: "Bias Detection",
    icon: faScaleBalanced,
    url: "https://medium.com/@altruisticxai/the-geometry-of-fairness-when-metrics-route-morality-0d78beb38661",
    platform: "medium",
  },
  {
    title: "Frameworks Don’t Govern — People Do",
    excerpt:
      "Why the NIST AI Risk Management Framework succeeds or fails based on human judgment, incentives, and organizational power—not checklists.",
    readTime: "7 min read",
    publishDate: "Jan 2025",
    category: "AI Governance",
    icon: faGavel,
    url: "https://ingakali.substack.com/p/frameworks-dont-governpeople-do",
    platform: "substack",
    featured: true,
  },
  {
    title: "The Hidden Costs of Algorithmic Bias",
    excerpt: "Exploring the financial, reputational, and human costs when AI systems perpetuate discrimination.",
    readTime: "6 min read",
    publishDate: "Nov 2024",
    category: "Ethics",
    icon: faBrain,
    url: "https://medium.com/@yourusername/hidden-costs-algorithmic-bias",
    platform: "medium",
  },
  {
    title: "Red Teaming AI Systems: A Security Perspective",
    excerpt: "Lessons from penetration testing applied to AI safety and adversarial robustness testing.",
    readTime: "10 min read",
    publishDate: "Oct 2024",
    category: "Security",
    icon: faShieldHalved,
    url: "https://yourusername.substack.com/p/red-teaming-ai-systems",
    platform: "substack",
  },
];
